// Define translations in a separate file to avoid the react-refresh warning
export type Language = 'en' | 'de' | 'es';

export type LanguageContextType = {
  language: string;
  setLanguage: (language: string) => void;
  translations: Record<string, Record<string, string>>;
};

// Basic translations
export const translations = {
  en: {
    // App Navigation
    'app.name': 'MärchenNails',
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.booking': 'Booking',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.admin': 'Admin',
    'nav.settings': 'Settings',
    
    // General UI
    'welcome': 'Welcome to MärchenNails',
    'bookNow': 'Book Now',
    'services': 'Our Services',
    'about': 'About Us',
    'contact': 'Contact',
    'login': 'Login',
    'register': 'Register',
    'profile': 'Profile',
    'logout': 'Logout',
    'dashboard': 'Dashboard',
    'appointments': 'Appointments',
    'settings': 'Settings',
    'errorMessage': 'An error occurred. Please try again.',
    'successMessage': 'Operation completed successfully!',
    
    // Calendar & Booking
    'booking.title': 'Book Your Appointment',
    'booking.selectService': 'Select Service',
    'booking.selectDate': 'Select Date',
    'booking.selectTime': 'Select Time',
    'booking.enterDetails': 'Your Details',
    'booking.firstName': 'First Name',
    'booking.lastName': 'Last Name',
    'booking.email': 'Email Address',
    'booking.phone': 'Phone Number',
    'booking.notes': 'Special Notes or Requests',
    'booking.confirmation': 'Booking Confirmation',
    'booking.submit': 'Confirm Booking',
    'booking.termsAccept': 'I accept the terms and conditions',
    'booking.next': 'Next',
    'booking.previous': 'Previous',
    'booking.summary': 'Booking Summary',
    'booking.noTimesAvailable': 'No available times on this date. Please select another date.',
    'booking.addToCalendar': 'Add to Calendar',
    'booking.googleCalendar': 'Google Calendar',
    'booking.downloadIcs': 'Download ICS File',
    
    // Calendar
    'calendar.today': 'Today',
    'calendar.month': 'Month',
    'calendar.week': 'Week',
    'calendar.day': 'Day',
    'calendar.appointment': 'Appointment',
    'calendar.duration': 'Duration',
    'calendar.with': 'with',
    'calendar.location': 'Location',
    'calendar.reminder': 'Reminder',
    
    // Email content
    'email.greeting': 'Hello',
    'email.bookingConfirmation': 'Thank you for booking an appointment with MärchenNails. We look forward to seeing you!',
    'email.appointmentDetails': 'Appointment Details:',
    'email.service': 'Service',
    'email.date': 'Date',
    'email.time': 'Time',
    'email.confirmationCode': 'Confirmation Code',
    'email.rescheduleInfo': 'If you need to reschedule or cancel your appointment, please contact us at least 24 hours in advance.',
    'email.closingMessage': 'We can\'t wait to see you!',
    'email.regards': 'Best regards,',
    'email.team': 'MärchenNails Team',
    'email.reminderSubject': 'Appointment Reminder',
    'email.reminderGreeting': 'This is a friendly reminder about your upcoming appointment with MärchenNails.',
    'email.arrivalInfo': 'Please arrive 5-10 minutes before your scheduled time. If you need to reschedule or cancel, please contact us as soon as possible.',
    'email.lookingForward': 'Looking forward to seeing you!',
    'email.cancellationSubject': 'Appointment Cancellation',
    'email.cancellationInfo': 'Your appointment at MärchenNails has been cancelled as requested.',
    'email.cancelledAppointment': 'Cancelled Appointment:',
    'email.bookAgain': 'We hope to see you again soon! Feel free to book another appointment at your convenience.',
    'email.feedbackThank': 'Thank you for taking the time to share your feedback with MärchenNails.',
    'email.feedbackHelp': 'Your opinion matters to us and helps us provide better service to all our clients.',
    'email.feedbackQuestion': 'Is there anything specific you\'d like to share about your experience? Feel free to reply to this email with any additional thoughts.',
    'email.promoBook': 'Book your appointment today to take advantage of this special offer!',
    'email.validUntil': 'Valid until',
    'email.bookNowButton': 'Book Now',
    'email.unsubscribe': 'If you wish to unsubscribe from promotional emails,',
    'email.clickHere': 'click here',
    'email.privacyPolicy': 'Privacy Policy',
    'email.termsOfService': 'Terms of Service',
    'email.excellentFeedback': 'We\'re thrilled to hear you had a great experience with us!',
    'email.goodFeedback': 'Thank you for your feedback. We\'re always working to improve our services.',
    'email.improveFeedback': 'We apologize that your experience didn\'t meet your expectations. Your feedback helps us improve.',
    'email.feedbackSubject': 'Thank You for Your Feedback',
    'email.useCode': 'Use code',
    'email.promoSubject': 'Special Offer',
  },
  de: {
    // App Navigation
    'app.name': 'MärchenNails',
    'nav.home': 'Startseite',
    'nav.services': 'Leistungen',
    'nav.booking': 'Buchung',
    'nav.contact': 'Kontakt',
    'nav.login': 'Anmelden',
    'nav.admin': 'Admin',
    'nav.settings': 'Einstellungen',
    
    // General UI
    'welcome': 'Willkommen bei MärchenNails',
    'bookNow': 'Jetzt Buchen',
    'services': 'Unsere Leistungen',
    'about': 'Über Uns',
    'contact': 'Kontakt',
    'login': 'Anmelden',
    'register': 'Registrieren',
    'profile': 'Profil',
    'logout': 'Abmelden',
    'dashboard': 'Übersicht',
    'appointments': 'Termine',
    'settings': 'Einstellungen',
    'errorMessage': 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.',
    'successMessage': 'Vorgang erfolgreich abgeschlossen!',
    
    // Calendar & Booking
    'booking.title': 'Termin Buchen',
    'booking.selectService': 'Leistung wählen',
    'booking.selectDate': 'Datum wählen',
    'booking.selectTime': 'Uhrzeit wählen',
    'booking.enterDetails': 'Ihre Angaben',
    'booking.firstName': 'Vorname',
    'booking.lastName': 'Nachname',
    'booking.email': 'E-Mail-Adresse',
    'booking.phone': 'Telefonnummer',
    'booking.notes': 'Besondere Wünsche oder Hinweise',
    'booking.confirmation': 'Buchungsbestätigung',
    'booking.submit': 'Buchung bestätigen',
    'booking.termsAccept': 'Ich akzeptiere die Allgemeinen Geschäftsbedingungen',
    'booking.next': 'Weiter',
    'booking.previous': 'Zurück',
    'booking.summary': 'Buchungsübersicht',
    'booking.noTimesAvailable': 'Keine verfügbaren Zeiten an diesem Tag. Bitte wählen Sie ein anderes Datum.',
    'booking.addToCalendar': 'Zum Kalender hinzufügen',
    'booking.googleCalendar': 'Google Kalender',
    'booking.downloadIcs': 'ICS-Datei herunterladen',
    
    // Calendar
    'calendar.today': 'Heute',
    'calendar.month': 'Monat',
    'calendar.week': 'Woche',
    'calendar.day': 'Tag',
    'calendar.appointment': 'Termin',
    'calendar.duration': 'Dauer',
    'calendar.with': 'mit',
    'calendar.location': 'Standort',
    'calendar.reminder': 'Erinnerung',
    
    // Email content
    'email.greeting': 'Hallo',
    'email.bookingConfirmation': 'Vielen Dank für Ihre Terminbuchung bei MärchenNails. Wir freuen uns auf Ihren Besuch!',
    'email.appointmentDetails': 'Termindetails:',
    'email.service': 'Leistung',
    'email.date': 'Datum',
    'email.time': 'Uhrzeit',
    'email.confirmationCode': 'Bestätigungscode',
    'email.rescheduleInfo': 'Falls Sie Ihren Termin verschieben oder stornieren möchten, kontaktieren Sie uns bitte mindestens 24 Stunden im Voraus.',
    'email.closingMessage': 'Wir freuen uns auf Sie!',
    'email.regards': 'Mit freundlichen Grüßen,',
    'email.team': 'Ihr MärchenNails Team',
    'email.reminderSubject': 'Terminerinnerung',
    'email.reminderGreeting': 'Dies ist eine freundliche Erinnerung an Ihren bevorstehenden Termin bei MärchenNails.',
    'email.arrivalInfo': 'Bitte kommen Sie 5-10 Minuten vor Ihrem Termin. Falls Sie den Termin verschieben oder absagen müssen, kontaktieren Sie uns bitte so bald wie möglich.',
    'email.lookingForward': 'Wir freuen uns auf Ihren Besuch!',
    'email.cancellationSubject': 'Terminabsage',
    'email.cancellationInfo': 'Ihr Termin bei MärchenNails wurde wie gewünscht storniert.',
    'email.cancelledAppointment': 'Stornierter Termin:',
    'email.bookAgain': 'Wir hoffen, Sie bald wieder zu sehen! Sie können jederzeit einen neuen Termin buchen.',
    'email.feedbackThank': 'Vielen Dank, dass Sie sich Zeit genommen haben, uns Ihr Feedback mitzuteilen.',
    'email.feedbackHelp': 'Ihre Meinung ist uns wichtig und hilft uns, unseren Service für alle Kunden zu verbessern.',
    'email.feedbackQuestion': 'Gibt es etwas Bestimmtes, das Sie über Ihre Erfahrung mitteilen möchten? Sie können gerne auf diese E-Mail antworten.',
    'email.promoBook': 'Buchen Sie Ihren Termin noch heute, um von diesem Sonderangebot zu profitieren!',
    'email.validUntil': 'Gültig bis',
    'email.bookNowButton': 'Jetzt Buchen',
    'email.unsubscribe': 'Wenn Sie keine Werbemails mehr erhalten möchten,',
    'email.clickHere': 'klicken Sie hier',
    'email.privacyPolicy': 'Datenschutzerklärung',
    'email.termsOfService': 'Nutzungsbedingungen',
    'email.excellentFeedback': 'Wir freuen uns sehr, dass Sie einen guten Eindruck von uns gewonnen haben!',
    'email.goodFeedback': 'Vielen Dank für Ihr Feedback. Wir arbeiten stets daran, unsere Dienstleistungen zu verbessern.',
    'email.improveFeedback': 'Es tut uns leid, dass Ihre Erfahrung nicht Ihren Erwartungen entsprochen hat. Ihr Feedback hilft uns, besser zu werden.',
    'email.feedbackSubject': 'Danke für Ihr Feedback',
    'email.useCode': 'Verwenden Sie den Code',
    'email.promoSubject': 'Sonderangebot',
  },
  es: {
    // App Navigation
    'app.name': 'MärchenNails',
    'nav.home': 'Inicio',
    'nav.services': 'Servicios',
    'nav.booking': 'Reservas',
    'nav.contact': 'Contacto',
    'nav.login': 'Iniciar Sesión',
    'nav.admin': 'Admin',
    'nav.settings': 'Configuración',
    
    // General UI
    'welcome': 'Bienvenido a MärchenNails',
    'bookNow': 'Reservar Ahora',
    'services': 'Nuestros Servicios',
    'about': 'Acerca de',
    'contact': 'Contacto',
    'login': 'Iniciar Sesión',
    'register': 'Registrarse',
    'profile': 'Perfil',
    'logout': 'Cerrar Sesión',
    'dashboard': 'Panel',
    'appointments': 'Citas',
    'settings': 'Configuración',
    'errorMessage': 'Ha ocurrido un error. Por favor, inténtelo de nuevo.',
    'successMessage': '¡Operación completada con éxito!',
    
    // Calendar & Booking
    'booking.title': 'Reservar Tu Cita',
    'booking.selectService': 'Seleccionar Servicio',
    'booking.selectDate': 'Seleccionar Fecha',
    'booking.selectTime': 'Seleccionar Hora',
    'booking.enterDetails': 'Tus Datos',
    'booking.firstName': 'Nombre',
    'booking.lastName': 'Apellido',
    'booking.email': 'Correo Electrónico',
    'booking.phone': 'Número de Teléfono',
    'booking.notes': 'Notas o Solicitudes Especiales',
    'booking.confirmation': 'Confirmación de Reserva',
    'booking.submit': 'Confirmar Reserva',
    'booking.termsAccept': 'Acepto los términos y condiciones',
    'booking.next': 'Siguiente',
    'booking.previous': 'Anterior',
    'booking.summary': 'Resumen de Reserva',
    'booking.noTimesAvailable': 'No hay horarios disponibles en esta fecha. Por favor, seleccione otra fecha.',
    'booking.addToCalendar': 'Añadir al Calendario',
    'booking.googleCalendar': 'Google Calendar',
    'booking.downloadIcs': 'Descargar archivo ICS',
    
    // Calendar
    'calendar.today': 'Hoy',
    'calendar.month': 'Mes',
    'calendar.week': 'Semana',
    'calendar.day': 'Día',
    'calendar.appointment': 'Cita',
    'calendar.duration': 'Duración',
    'calendar.with': 'con',
    'calendar.location': 'Ubicación',
    'calendar.reminder': 'Recordatorio',
    
    // Email content
    'email.greeting': 'Hola',
    'email.bookingConfirmation': '¡Gracias por reservar una cita con MärchenNails. Esperamos verte pronto!',
    'email.appointmentDetails': 'Detalles de la Cita:',
    'email.service': 'Servicio',
    'email.date': 'Fecha',
    'email.time': 'Hora',
    'email.confirmationCode': 'Código de Confirmación',
    'email.rescheduleInfo': 'Si necesitas reprogramar o cancelar tu cita, por favor contáctanos con al menos 24 horas de anticipación.',
    'email.closingMessage': '¡Estamos ansiosos por verte!',
    'email.regards': 'Saludos cordiales,',
    'email.team': 'Equipo MärchenNails',
    'email.reminderSubject': 'Recordatorio de Cita',
    'email.reminderGreeting': 'Este es un recordatorio amistoso sobre tu próxima cita con MärchenNails.',
    'email.arrivalInfo': 'Por favor, llega 5-10 minutos antes de tu hora programada. Si necesitas reprogramar o cancelar, contáctanos lo antes posible.',
    'email.lookingForward': '¡Esperamos verte pronto!',
    'email.cancellationSubject': 'Cancelación de Cita',
    'email.cancellationInfo': 'Tu cita en MärchenNails ha sido cancelada según lo solicitado.',
    'email.cancelledAppointment': 'Cita Cancelada:',
    'email.bookAgain': '¡Esperamos verte pronto de nuevo! Siéntete libre de reservar otra cita cuando lo desees.',
    'email.feedbackThank': 'Gracias por tomarte el tiempo de compartir tu opinión con MärchenNails.',
    'email.feedbackHelp': 'Tu opinión es importante para nosotros y nos ayuda a proporcionar un mejor servicio a todos nuestros clientes.',
    'email.feedbackQuestion': '¿Hay algo específico que te gustaría compartir sobre tu experiencia? Siéntete libre de responder a este correo con cualquier comentario adicional.',
    'email.promoBook': '¡Reserva tu cita hoy para aprovechar esta oferta especial!',
    'email.validUntil': 'Válido hasta',
    'email.bookNowButton': 'Reservar Ahora',
    'email.unsubscribe': 'Si deseas darte de baja de los correos promocionales,',
    'email.clickHere': 'haz clic aquí',
    'email.privacyPolicy': 'Política de Privacidad',
    'email.termsOfService': 'Términos de Servicio',
    'email.excellentFeedback': '¡Estamos encantados de saber que has tenido una gran experiencia con nosotros!',
    'email.goodFeedback': 'Gracias por tu feedback. Siempre estamos trabajando para mejorar nuestros servicios.',
    'email.improveFeedback': 'Lamentamos que tu experiencia no haya cumplido con tus expectativas. Tu feedback nos ayuda a mejorar.',
    'email.feedbackSubject': 'Gracias por tu Opinión',
    'email.useCode': 'Usa el código',
    'email.promoSubject': 'Oferta Especial',
  },
};
